spring:
  application:
    name: rebid-server-dev
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${naver.client.id}
            client-secret: ${naver.client.secret}
            redirect-uri: ${backend.base_url}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
              - profile_image
              - gender
              - age
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: jdbc:mysql://${aws.db.url}/${aws.db.name}?autoReconnect=true&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000


jwt:
  secret.key: ${jwt.secret.key}
  access.exp : 18000
  refresh.exp: 18000

backend:
  base-url: ${backend_base_url}
  domain : ${backend.domain}

frontend:
  base-url: ${frontend.base_url}
  auth-redirect-url: ${frontend.auth_redirect_url}

cloud:
  aws:
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-010928181446
      #s3 bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}