#spring:
#  application:
#    name: ReBid
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/ReBid
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        hbm2ddl:
#          auto: update
#        default_batch_fetch_size: 1000
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id: Q3ZtxDiytCq3nQp_XB02
#            client-secret: 8FaXnUmmI3
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope:
#              - nickname
#              - email
#              - profile_image
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#
#jwt:
#  secret.key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
#  access.exp : 7200
#  refresh.exp: 604800

